[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller>=6.13.0",
    "reportlab>=4.4.0",
    "tkcalendar>=1.6.1",
]
